//=============================================================================//
//                                                                             //
//   The Living Commonwealth — Fallout 4 adapter for the Living Commonwealth   //
//   Engine (LCE). An F4SE plugin; a client of the core, never a re-implement- //
//   ation of it. The seam is the public API: CreateEntity, DestroyEntity,     //
//   Remember, Update; intents are hints, not commands.                        //
//                                                                             //
//   QUOTE: <the author's line goes here>                                      //
//                                                                             //
//=============================================================================//

#include "Adapter.h"
#include "Tick.h"

#include <F4SE/F4SE.h>

#include <LCE/Logging/Logger.h>

#include <string_view>

namespace
{
    // The plugin's one world object — owned here, by the module, never a
    // reachable global in the core's sense.
    TLC::Adapter g_Adapter;

    //-------------------------------------------------------------------------
    // The world is awake: the heartbeat, then the translation — every
    // sim-relevant settler becomes a mind.
    //-------------------------------------------------------------------------
    void OnGameLoaded()
    {
        constexpr std::string_view Heartbeat = "The Living Commonwealth heartbeat: the world is awake.";

        // The visible log (My Games/Fallout4/F4SE/TheLivingCommonwealth.log).
        REX::INFO("{}", Heartbeat);

        // The documented channel: the mod logs through LCE's API, never
        // spdlog directly.
        LCE::Logging::Info(Heartbeat);

        g_Adapter.GameLoaded();
        LCE::Logging::Flush();
    }

    void OnPreLoadGame()
    {
        g_Adapter.PreLoadGame();
    }

    void OnDeleteGame()
    {
        g_Adapter.DeleteGame();
    }
}

//-------------------------------------------------------------------------
// The F4SE entry point. F4SE_PLUGIN_LOAD expands to
// extern "C" __declspec(dllexport) bool F4SEPlugin_Load(const F4SE::LoadInterface*).
// The version data (F4SEPlugin_Version) is generated by the
// commonlibf4.plugin build rule from xmake.lua.
//-------------------------------------------------------------------------
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    // Init wires the F4SE interfaces and the log sink (msvc + file). The
    // log name is kept free of spaces so the file stays clean. The
    // trampoline is where the Tick hooks' branches are allocated — a few
    // dozen bytes is all the four call-site hooks need.
    F4SE::Init(a_intfc, {
        .logName = "TheLivingCommonwealth",
        .trampoline = true,
        .trampolineSize = 128,
    });

    // The simulation's heartbeat: once per frame on the game thread, the
    // adapter decays the world and executes what the minds decided.
    TLC::Tick::Install([](double a_delta) { g_Adapter.Tick(a_delta); });

    // The engine's own logging, behind its API (ADR-0030: own the interface,
    // not the implementation).
    LCE::Logging::Initialize();

    if (const auto* messaging = F4SE::GetMessagingInterface(); messaging)
    {
        messaging->RegisterListener([](F4SE::MessagingInterface::Message* a_msg) {
            switch (a_msg->type)
            {
            case F4SE::MessagingInterface::kGameLoaded:
                REX::INFO("lifecycle: GameLoaded — the world wakes.");
                OnGameLoaded();
                break;
            case F4SE::MessagingInterface::kPreLoadGame:
                // kPreLoadGame fires only from BGSSaveLoadGame::LoadGame —
                // a save is actually being loaded. The name tells us which
                // one: in-game sessions showed a load firing ~10s after
                // the world woke, with no GameLoaded following it (the
                // sim died every run). The name is the clue to what
                // triggers it.
                REX::INFO(
                    "lifecycle: PreLoadGame — loading save '{}'.",
                    a_msg->data != nullptr
                        ? static_cast<const char*>(a_msg->data)
                        : "?");
                OnPreLoadGame();
                break;
            case F4SE::MessagingInterface::kDeleteGame:
                REX::INFO(
                    "lifecycle: DeleteGame — deleting save '{}'.",
                    a_msg->data != nullptr
                        ? static_cast<const char*>(a_msg->data)
                        : "?");
                OnDeleteGame();
                break;
            default:
                break;
            }
        });
    }
    else
    {
        REX::ERROR("The Living Commonwealth: failed to get the messaging interface.");
        return false;
    }

    REX::INFO("The Living Commonwealth v{} loaded.", F4SE::GetPluginVersion());
    return true;
}
