//=============================================================================//
//                                                                             //
//   The Living Commonwealth — Fallout 4 adapter for the Living Commonwealth   //
//   Engine (LCE). An F4SE plugin; a client of the core, never a re-implement- //
//   ation of it. The seam is the public API: CreateEntity, DestroyEntity,     //
//   Remember, Update; intents are hints, not commands.                        //
//                                                                             //
//   QUOTE: <the author's line goes here>                                      //
//                                                                             //
//=============================================================================//

#include "Adapter.h"

#include <F4SE/F4SE.h>

#include <LCE/Logging/Logger.h>

#include <string_view>

namespace
{
    // The plugin's one world object — owned here, by the module, never a
    // reachable global in the core's sense.
    TLC::Adapter g_Adapter;

    //-------------------------------------------------------------------------
    // The world is awake: the heartbeat, then the translation — every
    // sim-relevant settler becomes a mind.
    //-------------------------------------------------------------------------
    void OnGameLoaded()
    {
        constexpr std::string_view Heartbeat = "The Living Commonwealth heartbeat: the world is awake.";

        // The visible log (My Games/Fallout4/F4SE/TheLivingCommonwealth.log).
        REX::INFO("{}", Heartbeat);

        // The documented channel: the mod logs through LCE's API, never
        // spdlog directly.
        LCE::Logging::Info(Heartbeat);

        g_Adapter.StartWorld();
        LCE::Logging::Flush();
    }

    void OnPreLoadGame()
    {
        g_Adapter.EndWorld();
    }

    void OnDeleteGame()
    {
        g_Adapter.EndWorld();
    }
}

//-------------------------------------------------------------------------
// The F4SE entry point. F4SE_PLUGIN_LOAD expands to
// extern "C" __declspec(dllexport) bool F4SEPlugin_Load(const F4SE::LoadInterface*).
// The version data (F4SEPlugin_Version) is generated by the
// commonlibf4.plugin build rule from xmake.lua.
//-------------------------------------------------------------------------
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    // Init wires the F4SE interfaces and the log sink (msvc + file). The
    // log name is kept free of spaces so the file stays clean.
    F4SE::Init(a_intfc, { .logName = "TheLivingCommonwealth" });

    // The engine's own logging, behind its API (ADR-0030: own the interface,
    // not the implementation).
    LCE::Logging::Initialize();

    if (const auto* messaging = F4SE::GetMessagingInterface(); messaging)
    {
        messaging->RegisterListener([](F4SE::MessagingInterface::Message* a_msg) {
            switch (a_msg->type)
            {
            case F4SE::MessagingInterface::kGameLoaded:
                OnGameLoaded();
                break;
            case F4SE::MessagingInterface::kPreLoadGame:
                OnPreLoadGame();
                break;
            case F4SE::MessagingInterface::kDeleteGame:
                OnDeleteGame();
                break;
            default:
                break;
            }
        });
    }
    else
    {
        REX::ERROR("The Living Commonwealth: failed to get the messaging interface.");
        return false;
    }

    REX::INFO("The Living Commonwealth v{} loaded.", F4SE::GetPluginVersion());
    return true;
}
